name: V8WorkToolbox
description: "V8 工作工具包 - 一个实用的文件处理工具集合"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0+1
  yaml: ^3.1.0
  csv: ^6.0.0
  path: ^1.9.0
  archive: ^4.0.7
  aes256gcm: ^1.0.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  cryptography: ^2.0.0
  http: ^1.2.2
  rate_limiter: ^1.0.0
  xml: ^6.0.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
